server:
  port: 8083

spring:
  application:
    name: pdf-service
  messages:
    encoding: UTF-8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: application-db

security:
  oauth2:
    client:
      client-id: politechnika
      client-secret: politechnika1
    resource:
      tokenInfoUri: http://localhost:8085/oauth/check_token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
